# Cloudflare Pages configuration
name = "photosbarcelona"

[build]
command = "npm run build"
cwd = "."

[env.production]
# wrangler.toml
name = 'photosinbarcelona'
route = "photosbarcelona.com/*"
zone_id = ""
